<style>
    .formLabel{
        display: block;
        padding: 3px;
        margin: 4px 2px 3px 0;        
        background-color: #e2e1e1;
    }
    .formInput{
        padding: 4px;        
        border: 1px solid #4D90FE; 
        border-radius: 3px;
    }
    .formSelect{
        padding: 4px;
        border: 1px solid #4D90FE;
    }            
    .btnGeneral{
        margin: 0 4px 0 4px;
        padding: 3px 7px 3px 7px;
        background-color: #4D90FE;
        background-image: -moz-linear-gradient(center top , #4D90FE, #4787ED);
        border: 1px solid #3079ED;
        color: #FFFFFF;
        text-shadow: 0 1px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }
    .btnGeneral:hover{
        background-color: #357AE8;
        background-image: -moz-linear-gradient(center top , #4D90FE, #357AE8);
        border: 1px solid #2F5BB7;
        color: #FFFFFF;
        text-shadow: 0 1px rgba(0, 0, 0, 0.3);
        border-radius: 5px;
    }
    #contenedor_filtros{
        width: 50em;
        margin: 0 auto;
    }        


</style>
<div id="contenedor_filtros" class="">
    <form method="post" action="/certificados/laboral">    
        <fieldset>
            <legend>Buscar</legend>
            <table>
                <tr>
                    <td>
                        <label for="tipoDocumento" class="formLabel">Tipo Documento</label>
                        <select id="tipoDocumento" name="tipoDocumento" class="formSelect">
                            <option value="CC">CC</option>
                            <option value="TI">TI</option>
                            <option value="CE">CE</option>
                        </select>
                    </td>
                    <td>
                        <label for="numeroDocumento" class="formLabel">Numero Documento</label>
                        <input id="numeroDocumento" type="text" name="numeroDocumento" required="required" value="" class="formInput"/> 
                    </td>                
                    <td>
                        <label for="dirigido" class="formLabel">Dirigido a</label>
                        <input id="dirigido" type="text" name="dirigido" required="required" value="A QUIEN PUEDA INTERESAR" class="formInput"/> 
                    </td>                
                </tr>                
            </table>
            <p style="margin-top: 5px;" class="center">
                <input type="submit" name="enviar" value="Generar" class="btn-general"/>                                
            </p>
        </fieldset>
    </form>
</div>
<?php if($this->outDto->existe){ ?>
<div id="contenedor_pdf"> 
    <object data="/<?php echo $this->outDto->pdfPath ?>" type="application/pdf" width="100%" height="500">
    </object>
</div>   
<?php print_r($this->outDto->filaPersona) ?>
<br/>
<?php echo date_default_timezone_get(); ?>
<?php } ?>