<div id="" style="border: 0px solid green;">
    <form action="" method="post">
        <fieldset>
            <legend>Filtros</legend>
            <table>
                <tr>
                    <td>
                        <label for="tipoDocumento" class="form-label">Tip. Documento</label>
                    </td>
                    <td>
                        <label for="numeroDocumento" class="form-label">Num. Documento</label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <select name="tipoDocumento" id="tipoDocumento">
                            <option value="CC">CC</option>
                            <option value="NIT">NIT</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="numeroDocumento" value="" id="numeroDocumento">
                    </td>
                </tr>                
            </table>
            <p>
                <input type="submit" name="enviar" value="Buscar">
            </p>
        </fieldset>
    </form>
</div>