<?php $form = $this->outDto->form; ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction() ?>" class="well app-well app-margin">  
    <fieldset>
        <legend class="app-lgend">Buscar</legend>
        <table class="app-table-spacing">
            <tr>
                <td>
                    <label for="tipoDocumento">Tipo Documento</label>
                    <?php echo $form->getElement('tipoDocumento')->renderViewHelper() ?>
                </td>
                <td>
                    <label for="numeroDocumento">Número Documento</label>
                    <?php echo $form->getElement('numeroDocumento')->renderViewHelper() ?>   
                </td>
                <td>
                    <label for="dirigido">Dirigido a</label>
                    <?php echo $form->getElement('dirigido')->renderViewHelper() ?> 
                </td>
                <td class="app-td-bottom">
                    <div>
                        <?php echo $form->getElement('enviar')->renderViewHelper() ?> 
                    </div>    
                </td>
            </tr>
        </table>                
    </fieldset>
</form>  

<?php if ($this->outDto->existe) { ?>
    <div id="contenedor_pdf" class="app-margin">        
        <div>
            <i class="icon-file"></i>
            Visualización de la certificación: <a href="/<?php echo $this->outDto->pdfPath ?>" target="_blank"><?php echo $this->outDto->pdfName ?></a>
        </div>
        <object data="/<?php echo $this->outDto->pdfPath ?>" type="application/pdf" width="100%" height="600"></object>
    </div>   
<?php } ?>