<style>    
    .dv_frm{        
        padding: 1em;
        background-color: white;
        display: block;
        width: 300px;        
        margin: 11em auto; 
        border: 1px solid #c5c5c6;
        border-radius: 7px;
        box-shadow: 0px 0px 10px silver;
    }    
    
    .frm_label{        
        font-family: Arial,"Bitstream Vera Sans",Helvetica,Verdana,sans-serif;
        font-size: 17pt;        
        color: #dedddd;
    }
    
    .frm_input{
        color: #dedddd;
        padding: 5px;
        border-radius: 3px;
        font-size: 16px;
    }    
</style>

<div class="dv_frm">
    <form method="post" name="frm_log" action="/index/login" id="frm_log">        
        <p>
            <label for="in_user" class="frm_label">Usuario</label>
            </br>
            <input type="text" name="in_user" value="" id="in_user" placeholder="Nombre de usuario" required class="frm_input" />
        </p>
        <p>
            <label for="in_pass" class="frm_label">Clave</label>
            </br>
            <input type="password" name="in_pass" value="" id="in_pass" class="frm_input" required />
        </p>
        <p>
            <input type="submit" name="in_enviar" value="Ingresar" />
        </p>                                           
    </form>
</div>
