<div>    
    <table>
        <tr>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
            <td><?php echo rand(1000, 900000) ?></td>
        </tr>                  
    </table>
</div>
<hr/>

