<div class="row">
    <?php foreach ($this->dMenu as $key => $menu) { ?>
        <div class="span3">
            <div class="well app-margin center">
                <img alt="<?php echo $menu['nombre'] ?>" src="/img/folder_open.png">
                <h3 class="app-text-color"><?php echo $menu['nombre'] ?></h3> 
                <p class="justify app-text-color">
                    <?php echo $menu['descripcion'] ?>
                </p> 
            </div>
        </div>
    <?php } ?>    
</div>