<style>    
    .dv_frm{        
        padding: 1em;
        background-color: white;
        display: block;
        width: 250px;        
        margin: 11em auto; 
        border: 1px solid #c5c5c6;
        border-radius: 7px;
        box-shadow: 0px 0px 10px silver;
    }        
    .frm_label{        
        font-family: Arial,"Bitstream Vera Sans",Helvetica,Verdana,sans-serif;
        font-size: 17pt;        
        color: #666666;
        text-shadow:3px 0px 5px #999699;
    }    
    .frm_input{        
        color: #7b7b7c;
        background-color: #F5F5F5;
        padding: 5px;
        border: 1px solid #4D90FE;
        font-size: 22px;        
        width: 237px;
    }    
    .btn-submit{
        height: 30px;
        background-color: #4D90FE;
        background-image: -moz-linear-gradient(center top , #4D90FE, #4787ED);
        border: 1px solid #3079ED;
        color: #FFFFFF;
        text-shadow: 0 1px rgba(0, 0, 0, 0.1);
        border-radius: 3px;
    }
    .btn-submit:hover{
        background-color: #357AE8;
        background-image: -moz-linear-gradient(center top , #4D90FE, #357AE8);
        border: 1px solid #2F5BB7;
        color: #FFFFFF;
        text-shadow: 0 1px rgba(0, 0, 0, 0.3);
        border-radius: 3px;
    }
</style>

<div class="dv_frm">
    <form method="post" name="frm_log" action="/index/login" id="frm_log">        
        <p>
            <label for="in_user" class="frm_label">Usuario</label>
            </br>
            <input type="text" name="in_user" value="" id="in_user" placeholder="Nombre de usuario" required class="frm_input" />
        </p>
        <p>
            <label for="in_pass" class="frm_label">Clave</label>
            </br>
            <input type="password" name="in_pass" value="" id="in_pass" class="frm_input" required />
        </p>
        <p class="right">
            <input type="submit" name="in_enviar" value="Ingresar" class="btn-submit" />
        </p>                                           
    </form>
</div>