<div class="dv_frm">
    <form method="post" name="frm_log" action="/index/login" id="frm_log">        
        <p>
            <label for="nombreusuario" class="frm_label">Usuario</label>
            </br>
            <input type="text" name="nombreusuario" value="" id="nombreusuario" placeholder="Nombre de usuario" required class="frm_input" />
        </p>
        <p>
            <label for="claveusuario" class="frm_label">Clave</label>
            </br>
            <input type="password" name="claveusuario" value="" id="claveusuario" class="frm_input" required />
        </p>
        <p class="right">
            <input type="submit" name="enviar" value="Ingresar" class="btn-general" />
        </p>                                           
    </form>
</div>

<hr/>
<?php echo $this->form ?>
