<div class="dv_frm">
    <form method="post" name="frm_log" action="/index/login" id="frm_log">        
        <p>
            <label for="in_user" class="frm_label">Usuario</label>
            </br>
            <input type="text" name="in_user" value="" id="in_user" placeholder="Nombre de usuario" required class="frm_input" />
        </p>
        <p>
            <label for="in_pass" class="frm_label">Clave</label>
            </br>
            <input type="password" name="in_pass" value="" id="in_pass" class="frm_input" required />
        </p>
        <p class="right">
            <input type="submit" name="in_enviar" value="Ingresar" class="btn-submit" />
        </p>                                           
    </form>
</div>