<!DOCTYPE html>
<html lang="es"> 
    <head>
        <title>Principal de Drogas APP</title> 
        <meta charset="utf8"/>         
        <!-- Etiqueta compatibilidad IE con Chrome frame -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1"> 
              
        <?php $this->headLink()->appendStylesheet('/css/extjs4/ext-all.css'); ?>
        <?php $this->headLink()->appendStylesheet('/css/estilos.css'); ?>
        
        <?php //$this->headScript()->appendFile("https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"); ?>
        <?php $this->headScript()->appendFile("/js/jquery-1.7.1.min.js"); ?>
        <?php $this->headScript()->appendFile("/js/scripts.js"); ?>
        <?php $this->headScript()->appendFile("/js/ext-all.js"); ?>
        <?php $this->headScript()->appendFile("/js/menu.js"); ?>
        
        <!-- [inicio] Estilos css -->
        <?php echo $this->headLink() ?>        
        <?php echo $this->cssDinamicoHelper() ?>
        <!-- [fin] Estilos css -->
        
        <!-- [inicio] Archivos javascript -->
        <?php echo $this->headScript() ?>        
        <?php echo $this->javascriptDinamicoHelper() ?>
        <!-- [fin] Archivos javascript -->
    </head>
    <body>        
        <header style="height: 8em; display: block; border-bottom: 3px solid #357AE8;">            
            <img src="" alt="" />
            <p>Soy usuario logueado</p>
            <p class="right">
                <?php echo $this->nombreUsuarioHelper('NOMBRE_HEADER') ?>
            </p>
            <p class="right">
                <a href="/index/logout">Salir</a>
            </p>
        </header>            
        <div id="dv_main">
            <nav id="nav_menu"></nav>
            <div id="dv_mensajes_container">
                <div id="dv_mensajes" style="max-height: 11em; overflow: auto; width: 100%; border-bottom: 1px solid #e2e1e1; display: none;">
                    <?php $objMensajes = $this->mensajesHelper() ?>                    
                    <?php echo $objMensajes['html'] ?>                    
                </div>
                <p id="p_mensajes" data-opc="hide" data-num="<?php echo $objMensajes['count'] ?>" class="center" style="width: 180px; padding: 5px; background-color: #e2e1e1; margin: 0 auto; border-radius: 0 0 5px 5px; cursor: pointer;">
                    Ver mensajes (<?php echo $objMensajes['count'] ?>)
                </p>
            </div>
            <div id="dv_contenido" class="">             
                <?php echo $this->layout()->content; ?> 
            </div>
        </div>
        <footer class="center">
            texto de footer
        </footer>
    </body> 
</html>