<!DOCTYPE html>
<html lang="es"> 
    <head>
        <title>Principal de Drogas APP</title> 
        <meta charset="utf8"/>         
        <!-- Etiqueta compatibilidad IE con Chrome frame -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1"> 
                                        
        <?php $this->headLink()->appendStylesheet('/css/extjs4/ext-all.css'); ?>
        <?php $this->headLink()->appendStylesheet('/css/app.css'); ?>
        
        <?php $this->headScript()->appendFile("https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"); ?>
        <?php $this->headScript()->appendFile("/js/functions.js"); ?>
        <?php $this->headScript()->appendFile("/js/ext-all.js"); ?>
        <?php $this->headScript()->appendFile("/js/menu.js"); ?>
        
        <!-- [inicio] Estilos css -->
        <?php echo $this->headLink() ?>        
        <?php echo $this->cssDinamicoHelper() ?>
        <!-- [fin] Estilos css -->
        
        <!-- [inicio] Archivos javascript -->
        <?php echo $this->headScript() ?>        
        <?php echo $this->javascriptDinamicoHelper() ?>
        <!-- [fin] Archivos javascript -->
    </head>
    <body>        
        <header style="height: 8em; display: block;">            
            <img src="" alt="" />
            <p>Soy usuario logueado</p>
            <p class="right">
                <?php echo $this->nombreUsuarioHelper('NOMBRE_HEADER') ?>
            </p>
            <p class="right">
                <a href="/index/logout">Salir</a>
            </p>
        </header>            
        <div style="display: block; height: 3px; background-color: #357AE8"></div>
        <nav id="nav_menu"></nav>
        <div id="dv_main"> 
            
            <?php echo $this->layout()->content; ?>         
            
        </div>
        <footer class="center">
            texto de footer
        </footer>
    </body> 
</html>