<!DOCTYPE html>
<html lang="es"> 
    <head>
        <title>SGE APP</title> 
        <meta charset="utf8"/>         
        <!-- Etiqueta compatibilidad IE con Chrome frame -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1"> 
        
        <?php $this->headLink()->appendStylesheet('/css/bootstrap.css'); ?>                
        <?php $this->headLink()->appendStylesheet('/css/estilos.css'); ?>                
                
        <?php $this->headScript()->appendFile("//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"); ?>
        <?php (APPLICATION_ENV != 'development')? $this->headScript()->appendFile("/js/ga.js"): ''; ?>
        <?php $this->headScript()->appendFile("/js/bootstrap.js"); ?>
        <?php $this->headScript()->appendFile("/js/scripts.js"); ?>
        
        <!-- [inicio] Estilos css --> 
        <?php echo $this->headLink() ?>        
        <?php echo $this->cssDinamicoHelper() ?>
        <!-- [fin] Estilos css --> 
        
        <!-- [inicio] Archivos javascript --> 
        <?php echo $this->headScript() ?>
        <?php echo $this->javascriptDinamicoHelper() ?>
        <!-- [fin] Archivos javascript -->         
    </head>
    <body>        
        <div class="container">             
            <?php echo $this->layout()->content; ?>         
        </div>      
    </body> 
</html>