<!DOCTYPE html>
<html lang="es"> 
    <head>
        <title>Certifica APP</title> 
        <meta charset="utf8"/>         
        <!-- Etiqueta compatibilidad IE con Chrome frame -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1"> 
        
        <?php $this->headLink()->appendStylesheet('/css/bootstrap.css'); ?>                
        <?php $this->headLink()->appendStylesheet('/css/estilos.css'); ?>                
        
        <?php //$this->headScript()->appendFile("/js/jquery-1.7.1.min.js"); ?>
        <?php $this->headScript()->appendFile("https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"); ?>
        <?php $this->headScript()->appendFile("/js/bootstrap.js"); ?>
        <?php $this->headScript()->appendFile("/js/scripts.js"); ?>
        
        <!-- [inicio] Estilos css --> 
        <?php echo $this->headLink() ?>        
        <?php echo $this->cssDinamicoHelper() ?>
        <!-- [fin] Estilos css --> 
        
        <!-- [inicio] Archivos javascript --> 
        <?php echo $this->headScript() ?>
        <?php echo $this->javascriptDinamicoHelper() ?>
        <!-- [fin] Archivos javascript --> 
        <!-- [Inicio] Seguimiento Analitycs -->
        <script type="text/javascript">            
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-30086705-1']);
            _gaq.push(['_setDomainName', 'incolsoft.com']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();            
        </script>
        <!-- [Fin] Seguimiento Analitycs -->
    </head>
    <body>        
        <div class="container">             
            <?php echo $this->layout()->content; ?>         
        </div>      
    </body> 
</html>