<?php $form = $this->form; ?>
<div class="app-margin">
    <form action="/personas/modificar/uk/<?php echo fnEncriptar($this->id, __CRYP_KEY__) ?>" method="<?php echo $form->getMethod() ?>" class="well app-well">
        <fieldset>
            <legend class="app-legend">Modificar Persona</legend>
            <table class="app-table-spacing">
                <tr>
                    <td>
                        <label for="tipoDocumento">Tipo Documento</label>
                        <?php echo $form->getElement('tipoDocumento')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="numeroDocumento">N&uacute;mero Documento</label>
                        <?php echo $form->getElement('numeroDocumento')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="estado">Estado</label>
                        <?php echo $form->getElement('estado')->renderViewHelper() ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="primerNombre">Primer Nombre</label>
                        <?php echo $form->getElement('primerNombre')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="segundoNombre">Segundo Nombre</label>
                        <?php echo $form->getElement('segundoNombre')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="primerApellido">Primer Apellido</label>
                        <?php echo $form->getElement('primerApellido')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="segundoApellido">Segundo Apellido</label>
                        <?php echo $form->getElement('segundoApellido')->renderViewHelper() ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="fechaNacimiento">Fecha Nacimiento</label>
                        <?php echo $form->getElement('fechaNacimiento')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="fechaIngreso">Fecha de ingreso</label>
                        <?php echo $form->getElement('fechaIngreso')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="fechaRetiro">Fecha de retiro</label>
                        <?php echo $form->getElement('fechaRetiro')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="salario">Salario</label>
                        <div class="input-prepend input-append">
                            <span class="add-on">$</span>
                            <?php echo $form->getElement('salario')->renderViewHelper() ?>
                            <span class="add-on">.00</span>
                        </div>                        
                    </td>                    
                </tr>              
                <tr>
                    <td>
                        <label for="idCargo">Cargo</label>
                        <?php echo $form->getElement('idCargo')->renderViewHelper() ?>
                    </td>
                    <td>
                        <label for="idTipoContrato">Tipo Contrato</label>
                        <?php echo $form->getElement('idTipoContrato')->renderViewHelper() ?>
                    </td>
                    <td>&nbsp;</td>
                    <td class="app-td-bottom right">
                        <?php echo $form->getElement('grabar')->renderViewHelper() ?> 
                        <?php echo $form->getElement('limpiar')->renderViewHelper() ?> 
                    </td>
                </tr>              
            </table>
        </fieldset>            
    </form>
</div>